<h1>About Fontastica</h1>
<p>In design, typography is a hugely important factor. Choosing the right type for the design at hand can be very challenging. For some designers, it is as easy as "choosing free fonts"; for others, the task can be more daunting, especially if you're are not aware of the resources available. For designers who do not code, or for developers who do not design, it can be tricky to find fonts that will work well and look good.</p>
<p>There are already some free resources on the web. However, the problem with most these resources is that they are static. Everyone has a different idea of what good design is and which typefaces go well together. Static resources are good but they can only go so far: what if you dislike the combinations listed? What if you want to compare a combination? What if you already have a font and want to find a good match for it?</p>
<p>In the end, that was the aim: to create a resource where designers could browse font combinations and compare them side-by-side, where they are given choices rather than being made to search for combinations themselves.</p>

<h2>How to use the site</h2>
<p>The idea behind the site is to create a user-generated resource of fonts that work well together. This is achieved by serving random combinations of fonts to the user in the <a href="/rate">rating area</a>. If you like what you see, simply click "I like this!" - otherwise, click "This sucks!" It's pretty straightforward, really.</p>
<p>Alternatively, if you see a single font you like, you can view information about that font by clicking on the name in the sidebar, and there you can see a list of fonts that other users have thought work well with it. If you're <em>still</em> not satisfied, you can choose to view that font with others either as a header or body text, and keep going through until you find something you like.</p>

<h2>Site information</h2>
<p>Fontastica is the brainchild of me, Sophie Shanahan-Kluth. It's my final year project for university so quite a lot of work has gone into this. You can either <a href="http://twitter.com/Tawreh">keep up with me on Twitter</a>, or <a href="http://herbal-jazz.net/">visit my personal site</a>.</p>
<p>The site's fonts are served by Typekit, and it's set in Freight Sans Pro with Skolar for the headers. The site itself is built in PHP and MySQL with a smidgen of JavaScript thrown in here and there.</p>
<p>The fonts you can tag and rate are pulled from Google Web Fonts using <a href="https://developers.google.com/webfonts/docs/developer_api">their API</a>.</p>
<p>The dummy text on the rate pages is pulled in from the Gutenberg Project. Each one is a fable by Aesop, so hopefully you'll enjoy reading them as much as you enjoy browsing the combinations and picking your favourites.</p>
<p>If you come across an error, please <a href="mailto:ssk@herbal-jazz.net">get in touch</a> and let me know how you got it - the usual bug report garb. And then refresh the page a few times, because the error messages are from Firefly - more entertainment for you.</p>